Feature create product and post
SelfCapabilityEnhancement/OurShop-FE pull request #14
Opened 2022-10-13 02:38 UTC by chaoqunya

2022-10-13 03:41 UTC, CongcongDeng commented on src/assets/mockData.ts
>  const count = [2, 1, 3];
assets一般只放静态资源文件，比如图片等等，可在src下新建一个folder（能揭示意图就行）

2022-10-13 03:42 UTC, CongcongDeng commented on src/components/common/utils.ts
> +    const reader = new FileReader();
不需要base64转码，可删掉

2022-10-13 08:07 UTC, CongcongDeng requested changes

2022-10-13 09:47 UTC, chaoqunya commented on src/components/features/create-product/CreateProduct.tsx
> +      postProduct().then();
这个地方的async和await是参照`Header.tsx`的, 并且返回了`JSON.parse(response.data)`, 只是现在还没用到这个返回值.
https://github.com/SelfCapabilityEnhancement/OurShop-FE/blob/93ea9a7ff82dc65e92203e042999b166ed127f1c/src/components/features/header/Header.tsx#L14-L22

2022-10-14 08:22 UTC, CongcongDeng approved these changes

2022-10-14 08:22 UTC, merged