Create ecr
SelfCapabilityEnhancement/OurShop-FE pull request #32
Opened 2023-02-02 12:20 UTC by chaoqunya

2023-02-02 12:48 UTC, weijian-TW requested changes

2023-02-02 12:48 UTC, weijian-TW commented on .dockerignore
> +node_modules
这里少个换行

2023-02-02 12:48 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +    branches: [ 'create-ecr-35' ]
为什么需要指定当前分支？

2023-02-02 12:48 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +  REPO_NAME: 'ourshop-ecr-repo'
这个环境变量在哪里使用的呢？

2023-02-02 12:48 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          ref: create-ecr-35
为什么添加这个配置？

2023-02-02 12:48 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +    if: ${{ github.event.workflow_run.conclusion == 'success' }}
把 docker push image 跟 test 分开是为什么？一个 workflow 的文件只包含一个 job 这样是有啥讲吗？

2023-02-02 12:48 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          role-session-name: '${{ github.event.repository.name }}@build-and-push'
为什么设置 sts session name 呢？用默认的 `GitHubActions ` 就中吧。

2023-02-02 12:48 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          ./auto/build_push $REGISTRY/$REPOSITORY:$IMAGE_TAG
`$REGISTRY/$REPOSITORY:$IMAGE_TAG` 直接挪到 auto 脚本里去呗

2023-02-02 12:48 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          ./auto/build_push $REGISTRY/$REPOSITORY:$IMAGE_TAG
只有一行的话 `|` 可以不用加。

2023-02-02 12:48 UTC, weijian-TW commented on auto/build_push
> +docker push "$1"
少个空行

2023-02-02 12:48 UTC, weijian-TW commented on auto/dev-environment
> +trap "docker-compose down -v" Exit
加上 `-v` 之后，每次都会把 volume 删掉，那每次也都需要重新下包。那用 volume 的好处就没了，咱用 volume 就是为了保证多次运行的时候，如果对于 package.json, yarn.lock 没有任何修改就不用装了。

2023-02-02 12:50 UTC, weijian-TW requested changes

2023-02-02 12:50 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          role-to-assume: ${{ secrets.OURSHOP_ECR_REPO_ROLE }}
直接放一个 string 是不是就中？用个 secret 是考虑到？

2023-02-03 01:19 UTC, chaoqunya commented on .github/workflows/push-to-ecr.yml
> +    branches: [ 'create-ecr-35' ]
避免其他分支的'OurShop Unit test'运行后触发此'create-ecr-35'分支的push-to-ecr.yml

2023-02-03 01:23 UTC, chaoqunya commented on .github/workflows/push-to-ecr.yml
> +          ref: create-ecr-35
之前没加, 导致checkout到main

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/110969610/216488496-3d0f8cc0-f25c-423c-92f0-52b5bca4f1e6.png">

2023-02-03 01:24 UTC, chaoqunya commented on .github/workflows/push-to-ecr.yml
> +          role-to-assume: ${{ secrets.OURSHOP_ECR_REPO_ROLE }}
里面有我的id

2023-02-03 02:01 UTC, chaoqunya commented on .github/workflows/push-to-ecr.yml
> +    if: ${{ github.event.workflow_run.conclusion == 'success' }}
test运行通过是其他action得公共trigger, 所以单独提出来了. workflow内jobs间默认是并行的, 且在不同的runner, 无法共享上下文(aws OIDC), 而这里需要一致的上下文(aws OIDC), 得放在一个job内才行.

2023-02-03 02:03 UTC, chaoqunya commented on .github/workflows/push-to-ecr.yml
> +          ./auto/build_push $REGISTRY/$REPOSITORY:$IMAGE_TAG
可以, 但需要设置很多环境变量, 不仅包括现在前端的ecr repo, 还有之后后端的ecr repo

2023-02-03 02:45 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +    branches: [ 'create-ecr-35' ]
都没合到 master 上，还能触发？

2023-02-03 02:48 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +    branches: [ 'create-ecr-35' ]
[code](https://github.com/SelfCapabilityEnhancement/OurShop-FE/blob/main/.github/workflows/push-to-ecr.yml) 合到 master 了？

2023-02-03 02:49 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          ref: create-ecr-35
搁这里放个变量吧，要不别人在分支上运行测试也会 checkout 到 master。

2023-02-03 02:49 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +    if: ${{ github.event.workflow_run.conclusion == 'success' }}
不不不，我的意思是，为啥不用一个 workfolw 文件，而是拆成多个文件？

2023-02-03 02:51 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          role-to-assume: ${{ secrets.OURSHOP_ECR_REPO_ROLE }}
你的 id？那是啥？主要是现在除了你，谁都不知道到底用的哪个 role 😂 ，github action 的 secret 挺隐秘的。

2023-02-03 02:52 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          role-session-name: '${{ github.event.repository.name }}@build-and-push'
那个啥，不是改这个玩意，问题是为啥要指定 role-session-name?

2023-02-03 02:58 UTC, weijian-TW requested changes

2023-02-03 02:58 UTC, weijian-TW commented on auto/build_push
> +docker push "$1"
也不需要任何环境变量，之前不是提到，用 auto script 是为了可以在本地更方便的运行，就尽可能的简化在 CI 的配置，我觉得会好一点点。

```suggestion
#!/usr/bin/env bash
set -eu
cd "$(dirname "$0")/.."

IMAGE="494526681395.dkr.ecr.ap-east-1.amazonaws.com/ourshop-ecr-repo:${GITHUB_RUN_ID}"

docker build --target web -t "${IMAGE}" .

docker push "${IMAGE}"
```

2023-02-03 03:19 UTC, weijian-TW commented
刚刚我做了个测试，咱们现在使用的 workfolw_run 应该不是给咱们现在这种为了保证执行顺序而使用的。我并不能在界面上看到到底是哪个 workfolw 触发了当前的 workfolw。

是不是应该在 job 层做一些改动呢？我找了个 [aws-cdk](https://github.com/aws/aws-cdk/actions/runs/4064967457) 的 action。我们也应该是这种吧，只有在测试运行通过之后才会 publish image。
![image](https://user-images.githubusercontent.com/118704228/216504448-389eaf52-8a49-4b6a-a4f8-7f28f3b1e127.png)

2023-02-06 06:46 UTC, weijian-TW commented on .github/workflows/actions/unit-test.yml
> +      run: ./auto/test
为啥要给分开成多个文件然后 import 进去？

2023-02-06 06:46 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +          ref: ${{ env.BRANCH }}
https://github.com/actions/checkout/issues/20#issuecomment-524521113

github action 有个变量

2023-02-06 06:46 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +  workflow_dispatch:
这个字段是干嘛的呢？晚上我会问嗷

2023-02-06 06:46 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +    if: needs.unit-test.outputs.outcome == 'success'
必须要手动指定成功吗？https://github.com/weijiany/test-action/actions/runs/4082258649 我好像没有加哎~

2023-02-06 06:46 UTC, weijian-TW commented on .github/workflows/push-to-ecr.yml
> +    branches: 'create-ecr-35'
为啥还没合到 master 的 workflow 需要指定当前分支呢？不指定会怎么样呢？

2023-02-06 07:33 UTC, hulu-xu commented on .github/workflows/push-to-ecr.yml
> +    if: needs.unit-test.outputs.success == 'success'
needs和if冲突了 上一个job失败pipeline就会停止 不会往下执行

2023-02-06 07:35 UTC, hulu-xu commented on .github/workflows/unit-test.yml
>    push:
直接on: [push]呢

2023-02-07 02:49 UTC, weijian-TW approved these changes

2023-02-07 02:49 UTC, merged